version: '3.3'

services:
    custom-app:
        build: .
        # ports:
        #     - '80:80'
        #     - '443:443'
        volumes:
            - ./:/var/www
        depends_on:
            - db
    db:
        image: mysql:5.7
        volumes:
            - './.docker/db:/var/lib/mysql'
        restart: always
        ports:
            - '3306'
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: customdb
    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - '8080:80'
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: password
    custom-app-nginx:
        build: ./.docker/nginx
        restart: always
        ports:
            - '8000:80'
        volumes:
            - ./:/var/www
        depends_on:
            - custom-app
    